// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Vercel only needs a URL while generating the Prisma client during build.
    // Runtime production persistence will be configured separately.
    url: process.env["DATABASE_URL"] ?? "file:./prisma/ci.db",
  },
});
